# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea2893e17e9c35245324bccd415465ba7e6865f84ee73d208e5f7fb36d7af3f45d782c33503d3d66c21e4c861f9d124abe92632c72ea66e7b463c15d03fdc2c

test:
  secret_key_base: b988f2ab612d83f0f808b7b7bc99b2f92684501c64872363997f9c16e7414695717f74d1791393549f727270115e6d3b551725937e81cf085a293fe176872829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
